basePath: /api
consumes:
- application/json
host: host1506731561.sisdis.infralabs.cs.ui.ac.id
info:
  contact:
    email: avcwisesa@gmail.com
    name: Avicenna Wisesa
    url: http://github.com/avcwisesa
  description: |-
    This application is build for class assignment so that course participant
    can understand deeper about HTTP

    This supposedly comply to all the specification given on problem statement
  license:
    name: GPL
    url: https://www.gnu.org/licenses/gpl-3.0.en.html
  title: helloService.
  version: "1"
paths:
  /api/hello:
    post:
      consumes:
      - application/json
      description: Hello
      operationId: hello
      parameters:
      - in: body
        name: body
        required: true
      produces:
      - application/json
      responses:
        "200":
          description: successful operation
        "400":
          description: request is a required property
        "500":
          description: server error
      schemes:
      - http
  /api/plusone/{val}:
    get:
      description: Returns an incremented value
      operationId: plusone
      parameters:
      - description: value that need to be incremented
        format: int32
        in: path
        name: val
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: successful operation
        "400":
          description: Not a number
      schemes:
      - http
  /api/spesifikasi.yaml:
    get:
      description: Returns API specifications
      operationId: spesifikasi
      produces:
      - text/x-yaml
      responses:
        "200":
          description: successful operation
        "500":
          description: server error
      schemes:
      - http
produces:
- application/json
schemes:
- http
swagger: "2.0"
